"""
data_api.py — Small FastAPI service that wraps PostgreSQL (postgres_app)
behind proper REST endpoints.

Why this exists:
  Reading `featured.csv` directly or running raw SQL against Postgres is
  NOT an API call — it's file I/O / direct DB access. This service turns
  that data into genuine HTTP REST endpoints (JSON responses, documented
  routes, proper status codes) so that both `api_access.py` and the
  Streamlit dashboard can access the data the same way they already
  access Airflow and MLflow: over HTTP.

Run with:
    uvicorn data_api:app --host 0.0.0.0 --port 8010

Interactive API docs (auto-generated by FastAPI):
    http://<host>:8010/docs
"""
import logging
from datetime import date
from typing import Optional

import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from sqlalchemy import create_engine, text

import config

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("data_api")

app = FastAPI(
    title="Stock Recommender Data API",
    description="REST endpoints over PostgreSQL raw/featured stock data.",
    version="1.0",
)


def get_engine():
    url = (
        f"postgresql+psycopg2://{config.DB_CONFIG['user']}:{config.DB_CONFIG['password']}"
        f"@{config.DB_CONFIG['host']}:{config.DB_CONFIG['port']}/{config.DB_CONFIG['dbname']}"
    )
    return create_engine(url)


@app.get("/health")
def health():
    """Simple liveness check."""
    try:
        engine = get_engine()
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return {"status": "ok", "db": "reachable"}
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"Database unreachable: {e}")


@app.get("/tickers")
def list_tickers():
    """List all distinct tickers available in raw_prices."""
    engine = get_engine()
    try:
        df = pd.read_sql(text('SELECT DISTINCT ticker FROM raw_prices ORDER BY ticker'), engine)
        return {"count": len(df), "tickers": df["ticker"].tolist()}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/prices/{ticker}")
def get_prices(
    ticker: str,
    start: Optional[date] = Query(None, description="Filter: start date (YYYY-MM-DD)"),
    end: Optional[date] = Query(None, description="Filter: end date (YYYY-MM-DD)"),
    limit: int = Query(100, le=1000, description="Max rows to return (default 100, max 1000)"),
):
    """Return OHLCV price rows for a single ticker, most recent first."""
    engine = get_engine()
    query = 'SELECT * FROM raw_prices WHERE ticker = :ticker'
    params = {"ticker": ticker}
    if start:
        query += ' AND "Date" >= :start'
        params["start"] = str(start)
    if end:
        query += ' AND "Date" <= :end'
        params["end"] = str(end)
    query += ' ORDER BY "Date" DESC LIMIT :limit'
    params["limit"] = limit

    try:
        df = pd.read_sql(text(query), engine, params=params)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    if df.empty:
        raise HTTPException(status_code=404, detail=f"No price data found for ticker '{ticker}'")
    return {"ticker": ticker, "rows": len(df), "data": df.to_dict(orient="records")}


@app.get("/fundamentals/{ticker}")
def get_fundamentals(ticker: str):
    """Return the latest-snapshot fundamentals for a single ticker."""
    engine = get_engine()
    try:
        df = pd.read_sql(
            text('SELECT * FROM raw_fundamentals WHERE ticker = :ticker'),
            engine, params={"ticker": ticker},
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    if df.empty:
        raise HTTPException(status_code=404, detail=f"No fundamentals found for ticker '{ticker}'")
    return df.to_dict(orient="records")[0]


@app.get("/featured/{ticker}")
def get_featured(
    ticker: str,
    limit: int = Query(50, le=500, description="Max rows to return (default 50, max 500)"),
):
    """
    Return feature-engineered rows (technical indicators + fundamentals +
    label) for a single ticker, most recent first. Reads from the same
    featured.csv the models are trained on, served here as a real endpoint.
    """
    try:
        df = pd.read_csv(f"{config.DATA_DIR}/featured.csv", parse_dates=["Date"])
    except FileNotFoundError:
        raise HTTPException(status_code=503, detail="featured.csv not found — run the pipeline first.")

    df = df[df["ticker"] == ticker].sort_values("Date", ascending=False).head(limit)
    if df.empty:
        raise HTTPException(status_code=404, detail=f"No featured data found for ticker '{ticker}'")
    return {"ticker": ticker, "rows": len(df), "data": df.to_dict(orient="records")}


@app.get("/stats/row-counts")
def row_counts():
    """Return row counts for each raw/staged table — a quick pipeline health signal."""
    engine = get_engine()
    counts = {}
    for tbl in ["raw_prices", "raw_fundamentals", "raw_quarterly_fundamentals"]:
        try:
            with engine.connect() as conn:
                result = conn.execute(text(f"SELECT COUNT(*) FROM {tbl}"))
                counts[tbl] = result.scalar()
        except Exception as e:
            counts[tbl] = f"error: {e}"
    return counts


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8010)
